### ISSUE TITLE
Update digest to 0.8

### ISSUE THREAD

**Issue by eoger** [RustCrypto/KDFs#20]
Can't compile with `sha2 = "0.8"` since it uses digest 0.8.

**Comment by timvisee** [comment]
@eoger I've submitted a PR with this change, see https://github.com/RustCrypto/KDFs/pull/21.

I hope it will be accepted soon. In the mean time you may use the following in your `Cargo.toml` file as a temporary patch to use my branch that includes this update:

```toml
[patch.crates-io.hkdf]
git = "https://github.com/timvisee/KDFs"
rev = "277cf5d"
```

Be sure to remove this from your `Cargo.toml` once `hkdf` itself updates.
